### ISSUE TITLE
отступы

### ISSUE THREAD

**Issue by nikvst** [KIrill-Al/HW2#1]
https://github.com/KIrill-Al/HW2/blob/009c3cdd80652a3c45bcfc6465722be25f62b076/HW2_var3_1_lists.py#L31

1. Может стоит вынести генерацию значений в отдельную функцию? Это повысит читаемость кода.

2. "Невозрастающая последовательность" не означает, что последовательность обязательно убывает. 
Возможно, задача поставлена не до конца корректно.
Стоит переработать ее по одному из двух путей:
2.1 Последовательность, введенная пользователем, должна быть отсортирована по убыванию и после этого в нее будет вставлено новое число.
2.2 Число должно быть вставлено либо после такого же числа, либо добавлено в конец списка.

Замечания по оформлению: 
- лишние комментарии лучше не оставлять в коде; 
- код должен быть оформлен в одном стиле (в одних местах у тебя есть пробелы вокруг операторов ">", "<", "+", "-" и т.п., а в других нет. По стилистическим руководствам в python следует ставить пробелы вокруг них). На одной из ближайших лекций Егор раскажет об этом подробнее.

**Comment by nikvst** [comment]
с Эратосфеном и простыми числами все хорошо

**Comment by KIrill-Al** [comment]
@nikvst 
1. Вынес в отдельную функцию - gen_list
2. Не понял замечание по невозрастанию. Генератор изначально сделан с рандомом от 0 до 5, т. е. каждое следующее число с вероятностью 1/6 может быть таким же, а с вероятностью 5/6 - меньше. Соответственно, последовательность не убывающая. Хотя, конечно, случайно может сгенерироваться и строго убывающая.
Что касается пользовательского ввода. Предполагаю, что раз условие поставлено таким образом, то пользователь вводит последовательность в нужном виде) Скорректировал по первому варианту: введённая пользователем последовательность предварительно сортируется.

Мусор убрал, пробелы операторам добавил)

**Comment by nikvst** [comment]
Ок. На будущее - импорты делаются в самом начале файла в следующем поряке:
1. Импорты стандартных библиотек
2. Импорты сторонних модулей
3. Импорты из проекта
https://www.python.org/dev/peps/pep-0008/#imports
